Remove Inheritance Style Constraint Stings from Schemas
al-rigazzi/SmartSim pull request #9
Opened 2024-03-22 01:11 UTC by MattToast

Removes the Inheritance style constraint strings from schemas. Uses `t.Annotated` style pydantic constraints (pydantic is unable to validate when using `= Fields(...)` constraints when there are multiple fileds in the type for which the constraint can apply, and I wanted to try and be consistent across the code base).

## WARNING:
`t.Annotated` was introduced in Python 3.9! This change is incompatible with python 3.8, but seeing as dragon does not support any python versions less than 3.9 this should not be an issue. If needed, we can consider depending on `typing_extensions` to supply `Annotated`.

2024-03-22 08:41 UTC, al-rigazzi requested changes
Looks great! Since we are most likely going to do this anyway, would you mind also removing the Python 3.8 entry from the CI/CD matrix? I prefer seeing green check marks.

2024-03-22 17:43 UTC, MattToast commented
Can do! For now I'll just exclude 3.8 from the CI, but I also threw up a [ticket](https://github.com/CrayLabs/Poseidon/issues/663) here to make a more comprehensive change across all of the Smart* repos.

2024-03-25 12:33 UTC, al-rigazzi approved these changes
LGTM, awaiting @ankona's OK

2024-03-27 15:30 UTC, ankona commented on .github/workflows/run_tests.yml
> +        py_v: ['3.9', '3.10', '3.11'] # Python versions
If we make this change, should it be [mirrored](https://github.com/CrayLabs/SmartRedis/blob/develop/.github/workflows/run_tests.yml#L67) in SmartRedis?

2024-03-27 15:33 UTC, ankona commented on .github/workflows/run_tests.yml
> +        py_v: ['3.9', '3.10', '3.11'] # Python versions
ditto in `release` [action](https://github.com/al-rigazzi/SmartSim/blob/protodrg/.github/workflows/release.yml#L101)

2024-03-27 15:35 UTC, ankona commented on .github/workflows/run_tests.yml
> +        py_v: ['3.9', '3.10', '3.11'] # Python versions
ditto in [docs](https://github.com/CrayLabs/SmartSim/blob/develop/doc/installation_instructions/basic.rst?plain=1#L23)

2024-03-27 15:36 UTC, ankona commented on .github/workflows/run_tests.yml
> +        py_v: ['3.9', '3.10', '3.11'] # Python versions
Derp. Now i see earlier comments covering this... Carry on, nothing to see here!

2024-03-27 15:37 UTC, ankona approved these changes
LGTM!

2024-03-27 17:26 UTC, merged